version : "3"
services :
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./conf:/etc/nginx/conf.d:ro #настройка редиректа
      - ./www:/usr/share/nginx/html #домашняя категория
      - ./log:/var/log/nginx #log файлы
    restart: unless-stopped
