---
- name: install nginx in docker via docker-compose
  hosts: all
  user: root

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install required packages
      apt: name={{ item }}
      with_items:
        - docker
        - docker-compose

    - name: Start docker on boot
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create a directory if it does not exist
      ansible.builtin.file:
       path: /root/nginx
       state: directory
       mode: '0755'

    - name: Copy files
      ansible.builtin.copy:
        src: /Users/new/Desktop/Projects_home/testtask_scorewarrior/{{ item }}
        dest: /root/nginx
      with_items:
        - "docker-compose.yml"
        - "nginx/"

    - name: Run container
      become: True
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d"
        chdir: /root/nginx/
